name: .NET build

on:
  push:
    branches: [ GitHubAction_DemoProject ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x.x'
        
    - name: Install dependencies
      run: dotnet restore  ./VirtualEconomyFramework/VENFTApp-Server
   
    - name: Build
      run: dotnet build ./VirtualEconomyFramework/VENFTApp-Server/VENFTApp-Server.csproj --configuration Release --no-restore
    
